import {readFileSync,writeFileSync} from 'node:fs';
import {canonical,code,fen} from './encoding.mts';
import {happyR2Progress,routeCost} from './happy-r2-progress.mts';
import {getChess,findPiece} from '../../app/src/mate/chess';
import {createHash} from 'node:crypto';
// Usage: tsx scripts/bishop-knight-audit/derive-happy-r2.mts GRAPH.json OUTPUT.ts
const [input,output]=process.argv.slice(2);
if(!input||!output)throw new Error('Supply a candidate graph and an output TypeScript file');
const {nodes,graph,starts,r1Nodes}=JSON.parse(readFileSync(input,'utf8'));
const fixed=new Set<number>(r1Nodes),dist=happyR2Progress(graph,nodes.length,fixed);
const cost=(m:any)=>routeCost(m,dist);
const ids=new Map(nodes.map((n:number,i:number)=>[n,i]));
const roots=starts.map((s:string)=>ids.get(canonical(code(s))) as number);
const chosen=(i:number)=>fixed.has(i)||!graph[i].some((m:any)=>m.kind==='r2')?graph[i]:graph[i].filter((m:any)=>m.kind==='r2'&&cost(m)===dist[i]);
const reachable=new Set<number>(),queue=roots.filter((i:number)=>Number.isFinite(dist[i]));
for(let q=0;q<queue.length;q++){const i=queue[q];if(reachable.has(i))continue;reachable.add(i);for(const m of chosen(i))queue.push(...m.next);}
const policy=[...reachable].filter(i=>!fixed.has(i)&&graph[i].some((m:any)=>m.kind==='r2')).map(i=>({key:nodes[i],fen:fen(nodes[i]),plies:dist[i],moves:chosen(i)}));
const rows=new Map<string,number>();
for(const p of policy)for(const m of p.moves){
 const b=getChess(p.fen);b.move({from:m.uci.slice(0,2),to:m.uci.slice(2,4)});
 const key=([['w','k'],['w','b'],['w','n'],['b','k']] as const).map(([c,t])=>findPiece(b.fen(),c,t)!.square).join('');
 rows.set(key,Math.min(rows.get(key)??Infinity,p.plies));
}
const digest=createHash('sha256').update(readFileSync(input)).digest('hex');
writeFileSync(output,`// Generated by scripts/bishop-knight-audit/derive-happy-r2.mts.
// Candidate graph SHA-256: ${digest}
// Full post-White K/B/N/k placements; worst-case plies including White's move.
// r1 and lower-rule choices stay fixed; only r2 choices are optimized.
// Unexpanded frontiers are unresolved, never assumed to lead to mate.
export const happyR2DestinationBounds: readonly (readonly [string, number])[] = [
${[...rows].sort().map(([k,v])=>`  ['${k}', ${v}],`).join('\n')}
];
`);
console.log({roots:roots.length,solvedRoots:roots.filter((i:number)=>Number.isFinite(dist[i])).length,policyStates:policy.length,destinations:rows.size});
