import {readFileSync,writeFileSync} from 'node:fs';
const dir=process.env.AUDIT_DIR!;
const r=JSON.parse(readFileSync(dir+'/full-details.json','utf8'));
const manifest=JSON.parse(readFileSync(dir+'/manifest.json','utf8'));
const n=(x:number)=>x.toLocaleString('en-US');
const pct=(x:number,d:number)=>(100*x/d).toFixed(4)+'%';
const count=(x:any)=>`${n(x.orbits)} / ${n(x.physical)}`;
let md=`# Full bishop-and-knight audit\n\nPolicy commit: \`${manifest.commit}\`. Snapshot fingerprint: \`${manifest.fingerprint}\`.\n\nAll ${n(r.populations.all.total.physical)} post-White placements, reduced to ${n(r.populations.all.total.orbits)} actual D4 orbits. Counts below distinguish D4 orbits from physical board orientations; no blanket division by eight. Every tied best White move and app-selected Black reply is followed through changes of support. Black's previous-White-position return history is retained.\n\n## Loops by starting support status\n\n| Starting status | D4 positions | Physical positions | Directly on a loop, D4 / physical | Can reach a loop, D4 / physical | Direct-loop % of physical starts | Reach-loop % of physical starts |\n|---|---:|---:|---:|---:|---:|---:|\n`;
for(const key of ['all','supported','unsupported','7','5','3']){const p=r.populations[key];md+=`| ${key} | ${n(p.total.orbits)} | ${n(p.total.physical)} | ${count(p.directLoop)} | ${count(p.canLoop)} | ${pct(p.directLoop.physical,p.total.physical)} | ${pct(p.canLoop.physical,p.total.physical)} |\n`;}
md+=`\n${n(r.loopFamilies.total)} cyclic components after D4 deduplication. ${n(r.loopFamilies.withSupportedCycle)} contain a supported board on the cycle; ${n(r.loopFamilies.reachableFromSupportedStart)} are reachable from a fresh supported start; ${n(r.loopFamilies.reachableAfterAnySupportedPosition)} are reachable after support anywhere in the history-aware graph. Direct membership means that the board occurs on a history-aware cycle; it does not necessarily mean that its history-free Black reply reenters that same cycle. The stricter count is retained as directLoopFromFreshStart in the JSON. A component may contain several simple loops; these are component counts, not a count of all possible simple cycles.\n\n## Support-losing best White moves\n\nA loss means the last White result was supported and the next White result is unsupported. Black's reply does not itself reclassify support. Transition deduplication applies one shared D4 transformation to the prior White result, current White-turn board, and next White result.\n\n| Transition outcome | Distinct transitions, D4 / physical | Distinct supported source boards, D4 / physical |\n|---|---:|---:|\n`;
for(const [name,key] of [['Nonmating support losses','nonMating'],['Loss on a mating move','mating'],['Losses with playable examples','playableExamples'],['Census-only examples','censusOnlyExamples'],['No legal move retains support (nonmating losses)','noLegalSupportPreservingMove'],['A legal move retains support (nonmating losses)','legalSupportPreservingMoveExists'],['A support-preserving move avoids immediate capture/stalemate','safeSupportPreservingMoveExists'],['No support-preserving move avoids immediate capture/stalemate','noSafeSupportPreservingMove'],['A loop is reachable after the loss','canLoop'],['Mate is reachable after the loss','canMate'],['Capture/stalemate is reachable after the loss','canFail']]){const x=r.supportLoss[key!];md+=`| ${name} | ${count(x.events)} | ${count(x.sourcePositions)} |\n`;}
md+='\nReachable outcomes overlap when tied choices have different endings. Sources are post-White boards, so several Black replies or subsequent White moves can share one source. A source counted here can occur after earlier moves with history; it need not lose support under its fresh-start reply.\n\n| Previous support | Nonmating loss transitions, D4 / physical | Source boards, D4 / physical |\n|---|---:|---:|\n';
for(const g of r.supportLoss.bySize)md+=`| ${g.size} | ${count(g.events)} | ${count(g.sourcePositions)} |\n`;
md+='\n### Support-loss piece-position motifs\n\nThese groups use the placement before Black replies. The moved piece is included to identify the action to inspect. Source counts can overlap across groups. There are '+n(r.supportLoss.nonMating.whiteDecisions.orbits)+' distinct nonmating White decisions after dropping the preceding Black-reply context. A replay starts before the support-losing White move, with a short legal lead-in where necessary; the recorded prior White result is available in `support-loss-events.json`.\n\n| Motif | Transitions, D4 | Sources, D4 | Example loss |\n|---|---:|---:|---|\n';
for(const g of r.supportLoss.motifs)md+=`| ${g.label} | ${n(g.events.orbits)} | ${n(g.sourcePositions.orbits)} | ${g.example.url?'['+Math.ceil(g.example.lossPly/2)+'. '+g.example.move+']('+g.example.url+')':'Census-only (no replay)'} |\n`;
md+='\n## Piece-position motifs directly on cycles\n\nEvery cyclic post-White board is counted once, even if it belongs to multiple components. These groups describe pieces and protection, not which piece shuttles.\n\n| Motif | D4 positions | Physical positions | Components |\n|---|---:|---:|---|\n';
for(const g of r.positionMotifs)md+=`| ${g.label} | ${n(g.orbits)} | ${n(g.physical)} | ${g.families.join(', ')} |\n`;
md+='\n## Loop representatives\n\n| Component | Supported cycle boards, D4 | Unsupported cycle boards, D4 | Reachable after support | Replay |\n|---|---:|---:|---|---|\n';
for(const f of r.families)md+=`| ${f.id} | ${f.supportedCycleBoards.orbits} | ${f.unsupportedCycleBoards.orbits} | ${f.reachableAfterAnySupportedPosition?'yes':'no'} | ${f.witness.url?'['+f.witness.moves.join(' ')+']('+f.witness.url+')':'Lead-in required; see JSON'}${f.witness.freshLoadVerified?'':' (prior history required)'} |\n`;
md+='\n## Terminal outcomes and limits\n\n| Starting status | Can reach mate, D4 / physical | Can reach capture/stalemate, D4 / physical |\n|---|---:|---:|\n';
for(const key of ['all','supported','unsupported']){const p=r.populations[key];md+=`| ${key} | ${count(p.canMate)} | ${count(p.canFail)} |\n`;}
md+='\nThis is an exhaustive placement census (distinct squares and nonadjacent kings), not retrograde reachability from the initial chess position. It follows the app’s best-move policy, not every legal Black defense, and ignores clocks and repetition claims. Mate, stalemate, or a capturable minor terminates a branch. A supported root uses the app’s fresh Black reply; later nodes preserve its return-history rule. A few census placements may have no legal preceding White move (for example an impossible double check); those are explicitly marked census-only and receive no broken replay URL. No production preferences or support definitions were changed for this audit.\n';
writeFileSync(dir+'/full-report.md',md);
console.log('Full report: '+dir+'/full-report.md');
