import type {BishopKnightStage} from "./bishopKnightStages";

export type KnightAndBishopWhiteMoveScore = {
  readonly stage: BishopKnightStage;
  readonly matingNetPenalty: number;
  readonly sevenCagePenalty: number;
  readonly rareEscapePenalty: number;
  readonly declaredCentralNavigationPenalty: number | undefined;
  readonly protectedCentralManeuverPenalty: number | undefined;
  readonly bishopCentralPathDistance: number;
  readonly sixPointNinePenalty: number;
  readonly declaredStepPenalty: number;
  readonly relativeKnightPenalty: number;
  readonly startsWithMiddle16King: boolean;
  readonly startsWithCentralKingAndMiddle16Knight: boolean;
  readonly startsWithProtectedOppositeCentralKnight: boolean;
  readonly centralSetupBoundaryPenalty: number;
  readonly bishopCenterPenalty: number;
  readonly knightOppositeCentralDistance: number;
  readonly bishopCentralProximityScore: number;
  readonly startsWithBishopAdjacentToNoncentralKing: boolean;
  readonly bishopWhiteKingDistanceScore: number;
  readonly bishopMoveNearNoncentralKingPenalty: number;
  readonly immobileBishopPenalty: number;
  readonly bishopKingCentralCompletionPenalty: number;
  readonly bishopKingCentralNavigationScore: number;
  readonly bishopShuffleControlPenalty: number;
  readonly minorBlackDistanceScore: number;
  readonly unprotectedMinorCount: number;
  readonly minorCenterDistanceScore: number;
  readonly attackedMinorWithoutKingDefensePenalty: number;
  readonly knightKingProtectionDistance: number;
  readonly knightKingProximityScore: number;
  readonly knightStableBishopProtectionPenalty: number;
  readonly knightDefensePenalty: number;
  readonly knightCentralProximityScore: number;
  readonly kingKnightAdjacencyPenalty: number;
  readonly kingKnightDistanceScore: number;
  readonly knightDriftQualifies: boolean;
  readonly knightDriftRank: number;
  readonly knightDoubleOpposition: boolean;
  readonly knightFlanksBlackKing: boolean;
  readonly knightWhiteSideOfBlackDistance: number;
  readonly kingStepsTowardKnight: boolean;
  readonly kingCoordinationPenalty: number;
  readonly attackedBishopDefensePenalty: number;
  readonly undefendedKnightOnlyBishopDefenderPenalty: number;
  readonly undefendedMinorForkPenalty: number;
  readonly attackedBishopEscapeScore: number;
  readonly attackedBishopDistanceScore: number;
  readonly nearbyPairBishopEscapeScore: number;
  readonly nearbyPairCentralDefensePenalty: number;
  readonly attackedKnightDefensePenalty: number;
  readonly bishopOppositionPenalty: number;
  readonly knightNextAttackPenalty: number;
  readonly knightMiddle16ProximityScore: number;
  readonly oppositePrecageDistance: number;
  readonly middle16KnightKingAdjacencyPenalty: number;
  readonly oppositePrecageEuclideanDistanceSquared: number;
  readonly precageKingSteps: number;
  readonly precageSideDistance: number;
  readonly precageSideCornerDistanceSquared: number;
  readonly declaredPreparationPenalty: number;
  readonly preparationBishopWaitDistance: number;
  readonly supportedThreeCheckScore: number;
  readonly supportedDiagonalSizeScore: number;
  readonly supportedDiagonalKnightScore: number;
  readonly declaredSupportedKnightAdvancePenalty: number;
  readonly declaredSupportedThreePenalty: number;
  readonly declaredSupportedFivePenalty: number | undefined;
  readonly declaredSupportedSevenPenalty: number;
  readonly supportedSevenFlushColorPenalty: number;
  readonly supportedSevenFlushDistance: number;
  readonly supportedSevenBishopPenalty: number;
  readonly supportedThreeKingPlacementPenalty: number;
  readonly supportedFiveBishopPenalty: number;
  readonly supportedFiveKingTargetDistance: number;
  readonly supportedSevenKingTargetDistance: number;
  readonly supportedSevenKingTieDistance: number;
  readonly mateScore: number;
  readonly stalemateScore: number;
  readonly pieceSafetyScore: number;
  readonly kingCenterProximityScore: number;
  readonly kingCenterEuclideanScore: number;
  readonly bishopLongDiagonalPenalty: number;
  readonly bishopProtectedCenterPenalty: number;
  readonly bishopTargetCornerDistanceScore: number;
  readonly knightTargetProximityScore: number;
  readonly nonCentralBishopDistanceScore: number;
  readonly knightBishopProtectionPenalty: number;
  readonly knightBishopColorPenalty: number;
  readonly kingBishopColorPenalty: number;
  readonly bishopLongDiagonalIntersectionScore: number;
};

export type KnightAndBishopBlackMoveScore = {
  readonly captureMinorPenalty: number;
  readonly unprotectedMinorDistance: number;
  readonly centerDistance: number;
  readonly mobilityScore: number;
  readonly whiteKingDistanceScore: number;
  readonly matingCornerManhattanScore: number;
};

