// Generated by scripts/generate_two_bishops_diagrams.mts.
// Do not edit by hand.
export const TWO_BISHOPS_DIAGRAM_POSITIONS = {
  matingPosition: {
    pieces: [
      { square: 'h8', piece: 'k' },
      { square: 'd4', piece: 'B' },
      { square: 'c2', piece: 'B' },
    ],
    highlights: [
      { square: 'f8', kind: 'zone' },
      { square: 'f7', kind: 'zone' },
    ],
  },
  phaseTwoWall: {
    phase: '2/2',
    fen: "2k5/8/4K3/8/5B2/5B2/8/8 w - - 4 3",
    highlights: [
      { square: 'b8', kind: 'zone' },
      { square: 'b7', kind: 'zone' },
    ],
  },
  shepherd: {
    phase: '2/2',
    fen: "3k4/6BB/4K3/8/8/8/8/8 w - - 0 1",
    highlights: [
      { square: 'a8', kind: 'key' },
      { square: 'f8', kind: 'zone' },
    ],
    arrow: { from: 'e6', to: 'd6' },
  },
  ruleQ: {
    phase: '1/2',
    fen: "8/3B4/8/8/4K2B/8/3k4/8 w - - 0 1",
    highlights: [{ square: 'e2', kind: 'key' }],
    arrow: { from: 'd7', to: 'b5' },
  },
  proximateWall: {
    pieces: [
      { square: 'd4', piece: 'B' },
      { square: 'd5', piece: 'B' },
    ],
    highlights: [
      { square: 'a3', kind: 'zone' },
      { square: 'a4', kind: 'zone' },
      { square: 'a5', kind: 'zone' },
      { square: 'a6', kind: 'zone' },
      { square: 'b4', kind: 'zone' },
      { square: 'b5', kind: 'zone' },
      { square: 'f4', kind: 'zone' },
      { square: 'f5', kind: 'zone' },
      { square: 'g3', kind: 'zone' },
      { square: 'g4', kind: 'zone' },
      { square: 'g5', kind: 'zone' },
      { square: 'g6', kind: 'zone' },
    ],
  },
  degeneratePhaseTwoOpposition: {
    phase: '2/2',
    fen: "6k1/1B6/4K3/8/3B4/8/8/8 w - - 0 1",
    arrow: { from: 'e6', to: 'f6' },
  },
  degenerateIgnoreLightBishop: {
    phase: '2/2',
    fen: "4B1k1/6B1/5K2/8/8/8/8/8 w - - 0 1",
    arrow: { from: 'g7', to: 'h6' },
  },
  degenerateMateInFour: {
    phase: '2/2',
    fen: "8/k7/2KB4/8/2B5/8/8/8 w - - 2 2",
    highlights: [{ square: 'a6', kind: 'zone' }],
    arrow: { from: 'c6', to: 'c7' },
  },
  degenerateKnightStepControl: {
    phase: '2/2',
    fen: "6B1/6B1/8/8/5K2/7k/8/8 w - - 0 1",
    highlights: [
      { square: 'h5', kind: 'zone' },
      { square: 'g2', kind: 'zone' },
    ],
    arrow: { from: 'g8', to: 'd5' },
  },
  degenerateWallWaitingMove: {
    phase: '2/2',
    fen: "8/5B1k/5B2/5K2/8/8/8/8 w - - 0 1",
    highlights: [
      { square: 'g8', kind: 'zone' },
      { square: 'h8', kind: 'zone' },
    ],
    arrow: { from: 'f6', to: 'e5' },
  },
  degenerateCornerDiagonals: {
    phase: '2/2',
    fen: "8/1B5k/5K2/8/1B6/8/8/8 w - - 0 1",
    highlights: [
      { square: 'f8', kind: 'zone' },
      { square: 'h5', kind: 'zone' },
      { square: 'h6', kind: 'zone' },
    ],
    arrow: { from: 'b7', to: 'f3' },
  },
  degenerateXx: {
    phase: '2/2',
    fen: "5K1k/5B2/8/8/1B6/8/8/8 w - - 0 1",
    highlights: [{ square: 'h6', kind: 'zone' }],
    arrow: { from: 'b4', to: 'd2' },
  },
  degenerateKingLift: {
    phase: '2/2',
    fen: "8/8/8/5B2/8/5K2/3B4/7k w - - 2 2",
    arrow: { from: 'f3', to: 'g3' },
  },
  degenerateBishopRetreat: {
    phase: '2/2',
    fen: "5K2/5B2/5B1k/8/8/8/8/8 w - - 2 2",
    arrow: { from: 'f7', to: 'e8' },
  },
  degenerateLongDiagonal: {
    phase: '2/2',
    fen: "8/8/4B3/8/8/5K2/5B1k/8 w - - 0 1",
    highlights: [
      { square: 'e3', kind: 'zone' },
      { square: 'd4', kind: 'zone' },
      { square: 'c5', kind: 'zone' },
      { square: 'b6', kind: 'zone' },
    ],
  },
  degenerateEdgeRepair: {
    phase: '2/2',
    fen: "8/8/8/8/8/7k/5K2/3BB3 w - - 2 2",
    arrow: { from: 'e1', to: 'd2' },
  },
  degenerateEdgeUnmask: {
    phase: '2/2',
    fen: "8/8/8/8/8/7k/2B2K2/4B3 w - - 2 2",
    arrow: { from: 'e1', to: 'd2' },
  },
  degenerateDiagonalSetup: {
    phase: '2/2',
    fen: "8/4B3/5K2/7k/8/8/2B5/8 w - - 2 2",
    highlights: [
      { square: 'c8', kind: 'zone' },
      { square: 'd7', kind: 'zone' },
      { square: 'e6', kind: 'zone' },
      { square: 'f5', kind: 'zone' },
      { square: 'g4', kind: 'zone' },
      { square: 'h3', kind: 'zone' },
    ],
    arrow: { from: 'c2', to: 'f5' },
  },
  degenerateDiagonalWaitingMove: {
    phase: '2/2',
    fen: "4B1k1/8/4KB2/8/8/8/8/8 w - - 2 2",
    arrow: { from: 'e8', to: 'h5' },
  },
  degenerateFreeBishop: {
    phase: '2/2',
    fen: "2B5/8/8/8/8/8/5K2/4B2k w - - 2 2",
  },
  degenerateWaitingMove: {
    phase: '2/2',
    fen: "5B1k/1B3K2/8/8/8/8/8/8 w - - 0 1",
  },
  degenerateMiddleishTargetA: {
    phase: '1/2',
    fen: "8/8/8/1k1BK3/3B4/8/8/8 w - - 12 7",
    arrow: { from: 'e5', to: 'd6' },
  },
  degenerateMiddleishTargetB: {
    phase: '1/2',
    fen: "8/8/3K4/3BB3/8/3k4/8/8 w - - 14 8",
    arrow: { from: 'd6', to: 'c5' },
  },
  degeneratePhaseOneLoopEscape: {
    phase: '1/2',
    fen: "B7/B7/8/1k6/3K4/8/8/8 w - - 16 9",
    arrow: { from: 'a8', to: 'f3' },
  },
  degenerateKingFlank: {
    phase: '1/2',
    fen: "8/3k4/8/4K3/4BB2/8/8/8 w - - 0 1",
    arrow: { from: 'e5', to: 'f6' },
  },
  degenerateKingSidestep: {
    phase: '1/2',
    fen: "8/8/8/4BB2/5K2/8/5k2/8 w - - 32 17",
    arrow: { from: 'f4', to: 'g4' },
  },
  degenerateReformWall: {
    phase: '1/2',
    fen: "8/8/8/4BB2/6K1/8/4k3/8 w - - 34 18",
    arrow: { from: 'e5', to: 'f4' },
  },
} as const
