// Generated by scripts/generate_two_bishops_diagrams.mts.
// Do not edit by hand.
export const TWO_BISHOPS_DIAGRAM_CENSUS = {
  roots: 5000,
  expandedPositions: 29857,
  canonicalPositions: 29857,
  observations: 246395,
} as const

export const TWO_BISHOPS_DIAGRAM_POSITIONS = {
  bishopWall: {
    ruleId: 'bishop wall',
    fen: "1k6/3K4/8/8/BB6/8/8/8 w - - 0 1",
    canonicalKey: "1k6/3K4/8/8/BB6/8/8/8 w - -",
    observations: 144,
  },
  cornerFinish: {
    ruleId: 'edge finish',
    fen: "2k5/8/8/KBB5/8/8/8/8 w - - 0 1",
    canonicalKey: "2k5/8/8/KBB5/8/8/8/8 w - -",
    observations: 167,
  },
} as const
