// Generated by scripts/generate_two_bishops_diagrams.mts.
// Do not edit by hand.
export const TWO_BISHOPS_DIAGRAM_POSITIONS = {
  conclaveStep: {
    fen: "8/8/8/4BB2/8/3K4/5k2/8 w - - 16 9",
    arrow: { from: 'f5', to: 'e4' },
  },
  cornerFinish: {
    phase: '2/2',
    fen: "2k5/8/8/KBB5/8/8/8/8 w - - 0 1",
  },
} as const
