import { readFile, writeFile } from 'node:fs/promises'
import { fileURLToPath } from 'node:url'
import { getChess } from '../app/src/mate/chess.ts'
import { getTwoBishopsPhaseLabel } from '../app/src/mate/rules/twoBishopsGeometry.ts'

const OUTPUT = fileURLToPath(
  new URL(
    '../app/src/mate/rules/twoBishopsDiagramPositions.ts',
    import.meta.url,
  ),
)
const check = process.argv.includes('--check')

const conclaveStepFen = getChess(
  '8/8/8/4BB2/8/3K4/5k2/8 w - - 16 9',
).fen()
const reverseConclaveStepFen = getChess(
  '8/5k2/8/4K3/4BB2/8/8/8 w - - 0 1',
).fen()
const martianConclaveStepFen = getChess(
  '8/8/2K1k3/8/3BB3/8/8/8 w - - 4 3',
).fen()
const phaseTwoWallFen = getChess(
  '2k5/8/4K3/8/5B2/5B2/8/8 w - - 4 3',
).fen()
const degenerateMateInFourFen = getChess(
  '8/k7/2KB4/8/2B5/8/8/8 w - - 2 2',
).fen()
const degenerateKnightStepControlFen = getChess(
  '6B1/6B1/8/8/5K2/7k/8/8 w - - 0 1',
).fen()
const degenerateWallWaitingMoveFen = getChess(
  '8/5B1k/5B2/5K2/8/8/8/8 w - - 0 1',
).fen()
const degenerateCornerDiagonalsFen = getChess(
  '8/1B5k/5K2/8/1B6/8/8/8 w - - 0 1',
).fen()
const degenerateKingLiftFen = getChess(
  '8/8/8/5B2/8/5K2/3B4/7k w - - 2 2',
).fen()
const degenerateBishopRetreatFen = getChess(
  '5K2/5B2/5B1k/8/8/8/8/8 w - - 2 2',
).fen()
const degenerateLongDiagonalFen = getChess(
  '8/8/4B3/8/8/5K2/5B1k/8 w - - 0 1',
).fen()
const degenerateFreeBishopFen = getChess(
  '2B5/8/8/8/8/8/5K2/4B2k w - - 2 2',
).fen()
const degenerateWaitingMoveFen = getChess(
  '5B1k/1B3K2/8/8/8/8/8/8 w - - 0 1',
).fen()
const degenerateEdgeRepairFen = getChess(
  '8/8/8/8/8/7k/5K2/3BB3 w - - 2 2',
).fen()
const degenerateEdgeUnmaskFen = getChess(
  '8/8/8/8/8/7k/2B2K2/4B3 w - - 2 2',
).fen()
const degenerateDiagonalSetupFen = getChess(
  '8/4B3/5K2/7k/8/8/2B5/8 w - - 2 2',
).fen()
const degenerateDiagonalWaitingMoveFen = getChess(
  '4B1k1/8/4KB2/8/8/8/8/8 w - - 2 2',
).fen()
const degenerateKingFlankFen = getChess(
  '8/3k4/8/4K3/4BB2/8/8/8 w - - 0 1',
).fen()
const degenerateKingSidestepFen = getChess(
  '8/8/8/4BB2/5K2/8/5k2/8 w - - 32 17',
).fen()
const degenerateReformWallFen = getChess(
  '8/8/8/4BB2/6K1/8/4k3/8 w - - 34 18',
).fen()
for (const [label, fen] of [
  ['phase 2 wall', phaseTwoWallFen],
  ['degenerate mate in 4', degenerateMateInFourFen],
  ['degenerate knight-step control', degenerateKnightStepControlFen],
  ['degenerate wall waiting move', degenerateWallWaitingMoveFen],
  ['degenerate corner diagonals', degenerateCornerDiagonalsFen],
  ['degenerate king lift', degenerateKingLiftFen],
  ['degenerate bishop retreat', degenerateBishopRetreatFen],
  ['degenerate long diagonal', degenerateLongDiagonalFen],
  ['degenerate edge repair', degenerateEdgeRepairFen],
  ['degenerate edge unmask', degenerateEdgeUnmaskFen],
  ['degenerate diagonal setup', degenerateDiagonalSetupFen],
  ['degenerate diagonal waiting move', degenerateDiagonalWaitingMoveFen],
  ['degenerate free bishop', degenerateFreeBishopFen],
  ['degenerate waiting move', degenerateWaitingMoveFen],
] as const) {
  if (getTwoBishopsPhaseLabel(fen) !== '2/2') {
    throw new Error(`Two Bishops ${label} diagram must display Phase 2`)
  }
}
for (const [label, fen] of [
  ['reverse conclave step', reverseConclaveStepFen],
  ['martian conclave step', martianConclaveStepFen],
  ['degenerate king flank', degenerateKingFlankFen],
  ['degenerate king sidestep', degenerateKingSidestepFen],
  ['degenerate reform wall', degenerateReformWallFen],
] as const) {
  if (getTwoBishopsPhaseLabel(fen) !== '1/2') {
    throw new Error(`Two Bishops ${label} diagram must display Phase 1`)
  }
}

const source = `// Generated by scripts/generate_two_bishops_diagrams.mts.
// Do not edit by hand.
export const TWO_BISHOPS_DIAGRAM_POSITIONS = {
  matingPosition: {
    pieces: [
      { square: 'h8', piece: 'k' },
      { square: 'd4', piece: 'B' },
      { square: 'c2', piece: 'B' },
    ],
    highlights: [
      { square: 'f8', kind: 'zone' },
      { square: 'f7', kind: 'zone' },
    ],
  },
  phaseTwoWall: {
    phase: '2/2',
    fen: ${JSON.stringify(phaseTwoWallFen)},
    highlights: [
      { square: 'b8', kind: 'zone' },
      { square: 'b7', kind: 'zone' },
    ],
  },
  proximateWall: {
    pieces: [
      { square: 'd4', piece: 'B' },
      { square: 'd5', piece: 'B' },
    ],
    highlights: [
      { square: 'a3', kind: 'zone' },
      { square: 'a4', kind: 'zone' },
      { square: 'a5', kind: 'zone' },
      { square: 'a6', kind: 'zone' },
      { square: 'b4', kind: 'zone' },
      { square: 'b5', kind: 'zone' },
      { square: 'f4', kind: 'zone' },
      { square: 'f5', kind: 'zone' },
      { square: 'g3', kind: 'zone' },
      { square: 'g4', kind: 'zone' },
      { square: 'g5', kind: 'zone' },
      { square: 'g6', kind: 'zone' },
    ],
  },
  conclaveStep: {
    fen: ${JSON.stringify(conclaveStepFen)},
    arrow: { from: 'f5', to: 'e4' },
  },
  degenerateMateInFour: {
    phase: '2/2',
    fen: ${JSON.stringify(degenerateMateInFourFen)},
    highlights: [{ square: 'a6', kind: 'zone' }],
    arrow: { from: 'c6', to: 'c7' },
  },
  reverseConclaveStep: {
    phase: '1/2',
    fen: ${JSON.stringify(reverseConclaveStepFen)},
    arrow: { from: 'e5', to: 'd6' },
  },
  martianConclaveStep: {
    phase: '1/2',
    fen: ${JSON.stringify(martianConclaveStepFen)},
    highlights: [
      { square: 'e5', kind: 'zone' },
      { square: 'f5', kind: 'zone' },
      { square: 'f6', kind: 'zone' },
    ],
    arrow: { from: 'e4', to: 'd3' },
  },
  degenerateKnightStepControl: {
    phase: '2/2',
    fen: ${JSON.stringify(degenerateKnightStepControlFen)},
    highlights: [
      { square: 'h5', kind: 'zone' },
      { square: 'g2', kind: 'zone' },
    ],
    arrow: { from: 'g8', to: 'd5' },
  },
  degenerateWallWaitingMove: {
    phase: '2/2',
    fen: ${JSON.stringify(degenerateWallWaitingMoveFen)},
    highlights: [
      { square: 'g8', kind: 'zone' },
      { square: 'h8', kind: 'zone' },
    ],
    arrow: { from: 'f6', to: 'e5' },
  },
  degenerateCornerDiagonals: {
    phase: '2/2',
    fen: ${JSON.stringify(degenerateCornerDiagonalsFen)},
    highlights: [
      { square: 'f8', kind: 'zone' },
      { square: 'h5', kind: 'zone' },
    ],
    arrow: { from: 'b7', to: 'f3' },
  },
  degenerateKingLift: {
    phase: '2/2',
    fen: ${JSON.stringify(degenerateKingLiftFen)},
    arrow: { from: 'f3', to: 'g3' },
  },
  degenerateBishopRetreat: {
    phase: '2/2',
    fen: ${JSON.stringify(degenerateBishopRetreatFen)},
    arrow: { from: 'f7', to: 'e8' },
  },
  degenerateLongDiagonal: {
    phase: '2/2',
    fen: ${JSON.stringify(degenerateLongDiagonalFen)},
    highlights: [
      { square: 'e3', kind: 'zone' },
      { square: 'd4', kind: 'zone' },
      { square: 'c5', kind: 'zone' },
      { square: 'b6', kind: 'zone' },
    ],
  },
  degenerateEdgeRepair: {
    phase: '2/2',
    fen: ${JSON.stringify(degenerateEdgeRepairFen)},
    arrow: { from: 'e1', to: 'd2' },
  },
  degenerateEdgeUnmask: {
    phase: '2/2',
    fen: ${JSON.stringify(degenerateEdgeUnmaskFen)},
    arrow: { from: 'e1', to: 'd2' },
  },
  degenerateDiagonalSetup: {
    phase: '2/2',
    fen: ${JSON.stringify(degenerateDiagonalSetupFen)},
    highlights: [
      { square: 'c8', kind: 'zone' },
      { square: 'd7', kind: 'zone' },
      { square: 'e6', kind: 'zone' },
      { square: 'f5', kind: 'zone' },
      { square: 'g4', kind: 'zone' },
      { square: 'h3', kind: 'zone' },
    ],
    arrow: { from: 'c2', to: 'f5' },
  },
  degenerateDiagonalWaitingMove: {
    phase: '2/2',
    fen: ${JSON.stringify(degenerateDiagonalWaitingMoveFen)},
    arrow: { from: 'e8', to: 'h5' },
  },
  degenerateFreeBishop: {
    phase: '2/2',
    fen: ${JSON.stringify(degenerateFreeBishopFen)},
  },
  degenerateWaitingMove: {
    phase: '2/2',
    fen: ${JSON.stringify(degenerateWaitingMoveFen)},
  },
  degenerateKingFlank: {
    phase: '1/2',
    fen: ${JSON.stringify(degenerateKingFlankFen)},
    arrow: { from: 'e5', to: 'f6' },
  },
  degenerateKingSidestep: {
    phase: '1/2',
    fen: ${JSON.stringify(degenerateKingSidestepFen)},
    arrow: { from: 'f4', to: 'g4' },
  },
  degenerateReformWall: {
    phase: '1/2',
    fen: ${JSON.stringify(degenerateReformWallFen)},
    arrow: { from: 'e5', to: 'f4' },
  },
} as const
`

if (check) {
  const existing = await readFile(OUTPUT, 'utf8')
  if (existing !== source) {
    throw new Error(
      'Two Bishops diagram positions are stale; run npm run generate:two-bishops-diagrams',
    )
  }
} else {
  await writeFile(OUTPUT, source, 'utf8')
}

process.stdout.write(`conclave step: ${conclaveStepFen}\n`)
process.stdout.write(`reverse conclave step: ${reverseConclaveStepFen}\n`)
process.stdout.write(`martian conclave step: ${martianConclaveStepFen}\n`)
process.stdout.write(`phase 2 wall: ${phaseTwoWallFen}\n`)
process.stdout.write(`degenerate mate in 4: ${degenerateMateInFourFen}\n`)
process.stdout.write(
  `degenerate knight-step control: ${degenerateKnightStepControlFen}\n`,
)
process.stdout.write(
  `degenerate wall waiting move: ${degenerateWallWaitingMoveFen}\n`,
)
process.stdout.write(
  `degenerate corner diagonals: ${degenerateCornerDiagonalsFen}\n`,
)
process.stdout.write(`degenerate king lift: ${degenerateKingLiftFen}\n`)
process.stdout.write(
  `degenerate bishop retreat: ${degenerateBishopRetreatFen}\n`,
)
process.stdout.write(
  `degenerate long diagonal: ${degenerateLongDiagonalFen}\n`,
)
process.stdout.write(`degenerate edge repair: ${degenerateEdgeRepairFen}\n`)
process.stdout.write(`degenerate edge unmask: ${degenerateEdgeUnmaskFen}\n`)
process.stdout.write(
  `degenerate diagonal setup: ${degenerateDiagonalSetupFen}\n`,
)
process.stdout.write(
  `degenerate diagonal waiting move: ${degenerateDiagonalWaitingMoveFen}\n`,
)
process.stdout.write(`degenerate free bishop: ${degenerateFreeBishopFen}\n`)
process.stdout.write(`degenerate waiting move: ${degenerateWaitingMoveFen}\n`)
process.stdout.write(`degenerate king flank: ${degenerateKingFlankFen}\n`)
process.stdout.write(`degenerate king sidestep: ${degenerateKingSidestepFen}\n`)
process.stdout.write(`degenerate reform wall: ${degenerateReformWallFen}\n`)
