import { readFile, writeFile } from 'node:fs/promises'
import { fileURLToPath } from 'node:url'
import { getChess } from '../app/src/mate/chess.ts'
import { getTwoBishopsPhaseLabel } from '../app/src/mate/rules/twoBishopsGeometry.ts'

const OUTPUT = fileURLToPath(
  new URL(
    '../app/src/mate/rules/twoBishopsDiagramPositions.ts',
    import.meta.url,
  ),
)
const check = process.argv.includes('--check')

const conclaveStepFen = getChess(
  '8/8/8/4BB2/8/3K4/5k2/8 w - - 16 9',
).fen()
const cornerFinishFen = getChess(
  '2k5/8/8/KBB5/8/8/8/8 w - - 0 1',
).fen()
if (getTwoBishopsPhaseLabel(cornerFinishFen) !== '2/2') {
  throw new Error('Two Bishops corner-finish diagram must display Phase 2')
}

const source = `// Generated by scripts/generate_two_bishops_diagrams.mts.
// Do not edit by hand.
export const TWO_BISHOPS_DIAGRAM_POSITIONS = {
  conclaveStep: {
    fen: ${JSON.stringify(conclaveStepFen)},
    arrow: { from: 'f5', to: 'e4' },
  },
  cornerFinish: {
    phase: '2/2',
    fen: ${JSON.stringify(cornerFinishFen)},
  },
} as const
`

if (check) {
  const existing = await readFile(OUTPUT, 'utf8')
  if (existing !== source) {
    throw new Error(
      'Two Bishops diagram positions are stale; run npm run generate:two-bishops-diagrams',
    )
  }
} else {
  await writeFile(OUTPUT, source, 'utf8')
}

process.stdout.write(`conclave step: ${conclaveStepFen}\n`)
process.stdout.write(`phase 2: ${cornerFinishFen}\n`)
