import { readFile, writeFile } from 'node:fs/promises'
import { fileURLToPath } from 'node:url'
import { getMateRuleSet } from '../app/src/mate/rules/index.ts'
import {
  createTwoBishopsDiagramCensus,
  selectMostCommonRulePositions,
} from './mate-verifier/two-bishops-diagram-census.mts'

const TARGET_RULES = ['bishop wall', 'corner finish'] as const
const ROOT_LIMIT = 5_000
const OUTPUT = fileURLToPath(
  new URL(
    '../app/src/mate/rules/twoBishopsDiagramPositions.ts',
    import.meta.url,
  ),
)
const check = process.argv.includes('--check')

const census = createTwoBishopsDiagramCensus({
  maxRoots: ROOT_LIMIT,
  onProgress: ({ expandedPositions, observations, roots }) => {
    process.stderr.write(
      `Census: ${roots.toLocaleString()} roots, ${expandedPositions.toLocaleString()} expansions, ${observations.toLocaleString()} observations\n`,
    )
  },
})
const ruleSet = getMateRuleSet('two-bishops')
let lastProgress = 0
const selected = selectMostCommonRulePositions(
  census.positions.values(),
  TARGET_RULES,
  (fen) => ruleSet.currentWhiteHint(fen)?.id,
  (classified) => {
    if (classified - lastProgress < 250) return
    lastProgress = classified
    process.stderr.write(
      `Classified ${classified.toLocaleString()} diagram candidates\n`,
    )
  },
)

for (const ruleId of TARGET_RULES) {
  if (!selected.has(ruleId)) {
    throw new Error(`No certified position activates ${ruleId}`)
  }
}

const source = renderGeneratedSource(
  census,
  Object.fromEntries(
    TARGET_RULES.map((ruleId) => [ruleId, selected.get(ruleId)!]),
  ),
)

if (check) {
  const existing = await readFile(OUTPUT, 'utf8')
  if (existing !== source) {
    throw new Error(
      'Two Bishops diagram positions are stale; run npm run generate:two-bishops-diagrams',
    )
  }
} else {
  await writeFile(OUTPUT, source, 'utf8')
}

for (const ruleId of TARGET_RULES) {
  const candidate = selected.get(ruleId)!
  process.stdout.write(
    `${ruleId}: ${candidate.canonicalFen} (${candidate.observations} observations)\n`,
  )
}

function renderGeneratedSource(
  census: {
    readonly expandedPositions: number
    readonly observations: number
    readonly positions: ReadonlyMap<string, unknown>
    readonly roots: number
  },
  positions: Readonly<
    Record<
      (typeof TARGET_RULES)[number],
      {
        readonly canonicalFen: string
        readonly canonicalKey: string
        readonly observations: number
      }
    >
  >,
): string {
  return `// Generated by scripts/generate_two_bishops_diagrams.mts.
// Do not edit by hand.
export const TWO_BISHOPS_DIAGRAM_CENSUS = {
  roots: ${census.roots},
  expandedPositions: ${census.expandedPositions},
  canonicalPositions: ${census.positions.size},
  observations: ${census.observations},
} as const

export const TWO_BISHOPS_DIAGRAM_POSITIONS = {
  bishopWall: {
    ruleId: 'bishop wall',
    fen: ${JSON.stringify(positions['bishop wall'].canonicalFen)},
    canonicalKey: ${JSON.stringify(positions['bishop wall'].canonicalKey)},
    observations: ${positions['bishop wall'].observations},
  },
  cornerFinish: {
    ruleId: 'corner finish',
    fen: ${JSON.stringify(positions['corner finish'].canonicalFen)},
    canonicalKey: ${JSON.stringify(positions['corner finish'].canonicalKey)},
    observations: ${positions['corner finish'].observations},
  },
} as const
`
}
