#!/usr/bin/env python3
"""Generate the compact KBBvK White-turn DTM proof table used by the app."""

from __future__ import annotations

import argparse
import base64
from pathlib import Path

import chess
import chess.gaviota


def transform(square: int, transform_index: int) -> int:
    file = chess.square_file(square)
    rank = chess.square_rank(square)
    variants = (
        (file, rank),
        (7 - rank, file),
        (7 - file, 7 - rank),
        (rank, 7 - file),
        (7 - file, rank),
        (file, 7 - rank),
        (rank, file),
        (7 - rank, 7 - file),
    )
    result_file, result_rank = variants[transform_index]
    return chess.square(result_file, result_rank)


def canonical_black_squares() -> list[int]:
    return sorted(
        {
            min(transform(square, index) for index in range(8))
            for square in chess.SQUARES
        }
    )


def color_squares(color: bool) -> list[int]:
    return [
        square
        for square in chess.SQUARES
        if (
            chess.square_rank(square) % 2
            == chess.square_file(square) % 2
        )
        is color
    ]


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("gaviota_dir", type=Path)
    parser.add_argument("output", type=Path)
    args = parser.parse_args()

    black_squares = canonical_black_squares()
    dark_squares = color_squares(False)
    light_squares = color_squares(True)
    data = bytearray(len(black_squares) * 64 * 32 * 32)

    with chess.gaviota.open_tablebase(str(args.gaviota_dir)) as tablebase:
        for black_index, black_king in enumerate(black_squares):
            for white_king in chess.SQUARES:
                for dark_index, dark_bishop in enumerate(dark_squares):
                    for light_index, light_bishop in enumerate(light_squares):
                        offset = (
                            ((black_index * 64 + white_king) * 32 + dark_index)
                            * 32
                            + light_index
                        )
                        if len(
                            {
                                black_king,
                                white_king,
                                dark_bishop,
                                light_bishop,
                            }
                        ) != 4:
                            continue
                        board = chess.Board.empty()
                        board.turn = chess.WHITE
                        board.set_piece_at(black_king, chess.Piece(chess.KING, chess.BLACK))
                        board.set_piece_at(white_king, chess.Piece(chess.KING, chess.WHITE))
                        board.set_piece_at(dark_bishop, chess.Piece(chess.BISHOP, chess.WHITE))
                        board.set_piece_at(light_bishop, chess.Piece(chess.BISHOP, chess.WHITE))
                        if not board.is_valid():
                            continue
                        try:
                            distance = tablebase.probe_dtm(board)
                        except KeyError:
                            continue
                        if distance > 0:
                            data[offset] = min(distance, 254)

    encoded = base64.b64encode(data).decode("ascii")
    chunks = [encoded[index : index + 100] for index in range(0, len(encoded), 100)]
    maximum_distance = max(data)
    winning_position_count = sum(distance > 0 for distance in data)
    args.output.write_text(
        "// Generated by scripts/generate_two_bishops_proof_table.py.\n"
        "// Source format: Gaviota KBBK DTM tablebase, probed offline.\n"
        f"export const TWO_BISHOPS_PROOF_MAX_DISTANCE = {maximum_distance}\n"
        f"export const TWO_BISHOPS_PROOF_POSITION_COUNT = {winning_position_count}\n"
        "export const TWO_BISHOPS_PROOF_DATA_BASE64 =\n  "
        + " +\n  ".join(repr(chunk) for chunk in chunks)
        + "\n",
        encoding="utf-8",
    )


if __name__ == "__main__":
    main()
